// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShelfLife.Server.Data;

#nullable disable

namespace ShelfLife.Server.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20231228151013_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ShelfLife.Server.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J. R. R. Tolkien",
                            CoverImage = "https://upload.wikimedia.org/wikipedia/en/8/8e/The_Fellowship_of_the_Ring_cover.gif",
                            Genre = "Fantasy",
                            Link = "https://en.wikipedia.org/wiki/The_Lord_of_the_Rings",
                            NumberOfChapters = 62,
                            NumberOfPages = 1178,
                            PublicationYear = 1954,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J. R. R. Tolkien",
                            CoverImage = "https://upload.wikimedia.org/wikipedia/en/3/30/Hobbit_cover.JPG",
                            Genre = "Fantasy",
                            Link = "https://en.wikipedia.org/wiki/The_Hobbit",
                            NumberOfChapters = 19,
                            NumberOfPages = 310,
                            PublicationYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J. R. R. Tolkien",
                            CoverImage = "https://upload.wikimedia.org/wikipedia/en/0/0b/The_Silmarillion_%28J.R.R._Tolkien%29_cover.jpg",
                            Genre = "Fantasy",
                            Link = "https://en.wikipedia.org/wiki/The_Silmarillion",
                            NumberOfChapters = 24,
                            NumberOfPages = 365,
                            PublicationYear = 1977,
                            Title = "The Silmarillion"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J. R. R. Tolkien",
                            CoverImage = "https://upload.wikimedia.org/wikipedia/en/9/9c/The_Children_of_H%C3%BArin_cover.jpg",
                            Genre = "Fantasy",
                            Link = "https://en.wikipedia.org/wiki/The_Children_of_H%C3%BArin",
                            NumberOfChapters = 23,
                            NumberOfPages = 313,
                            PublicationYear = 2007,
                            Title = "The Children of Húrin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
